import Link from 'next/link';
import Header from '@/components/Header';

export const metadata = {
    title: 'Terms of Service',
    description: 'Terms and conditions for using VCursor.',
};

export default function TermsPage() {
    return (
        <main className="main-layout bg-[hsl(var(--background))] min-h-screen">
            <Header />
            <div className="container py-12 px-4 md:px-6">
                <div className="max-w-4xl mx-auto doc-page">
                    <h1 className="doc-title">Terms of Service</h1>

                    <div className="doc-section">
                        <h2>Introduction</h2>
                        <p>
                            Welcome to VCursor. These Terms of Service ("Terms") cover your use of our
                            CLI, website, and services. By using VCursor, you agree to these Terms.
                        </p>
                    </div>

                    <div className="doc-section">
                        <h2>Account & Responsibility</h2>
                        <p>
                            You represent that you are of legal age to form a binding contract.
                            You are responsible for maintaining the security of your account and API keys.
                            Any activity under your account is your responsibility.
                        </p>
                    </div>

                    <div className="doc-section">
                        <h2>Conditions of Use</h2>
                        <p>You agree NOT to:</p>
                        <ul className="list-disc pl-6 space-y-2 mb-4 text-[hsl(var(--muted-foreground))]">
                            <li>Use the service for illegal acts or to infringe on others' rights.</li>
                            <li>Distribute malware or attempt unauthorized access.</li>
                            <li>Reverse engineer the CLI or backend services.</li>
                            <li>Generate deepfakes or deceptive content impersonating others without consent.</li>
                        </ul>
                    </div>

                    <div className="doc-section">
                        <h2>Intellectual Property</h2>
                        <h3 className="text-xl font-semibold mb-2 mt-4">1. Your Input</h3>
                        <p>You retain rights to the content you submit (prompts, images).</p>

                        <h3 className="text-xl font-semibold mb-2 mt-4">2. Generated Output</h3>
                        <p>
                            To the extent permitted by law, you own the rights to the content generated by VCursor
                            based on your inputs.
                        </p>

                        <h3 className="text-xl font-semibold mb-2 mt-4">3. Service Improvement</h3>
                        <p>
                            You grant us a license to use your inputs to improve our services and AI models,
                            including debugging and optimization.
                        </p>
                    </div>

                    <div className="doc-section">
                        <h2>Disclaimers</h2>
                        <p>
                            The service is provided "as is". We make no warranties regarding uptime,
                            accuracy of AI outputs, or fitness for a particular purpose. AI can make mistakes—please verify critical outputs.
                        </p>
                    </div>

                    <div className="doc-section">
                        <h2>Limitation of Liability</h2>
                        <p>
                            VCursor shall not be liable for indirect, incidental, or consequential damages
                            resulting from your use of the service.
                        </p>
                    </div>

                    <div className="doc-section">
                        <h2>Contact</h2>
                        <p>
                            Questions? Reach us on
                            <Link href="https://discord.gg/Npf6PVsCYz" className="text-[hsl(var(--primary))] hover:underline ml-1">
                                Discord
                            </Link>.
                        </p>
                    </div>

                    <div className="mt-12 pt-8 border-t border-[hsl(var(--border))]">
                        <Link href="/" className="text-[hsl(var(--primary))] hover:underline">
                            &larr; Return to Home
                        </Link>
                    </div>
                </div>
            </div>
            <footer className="footer">
                <div className="container footer-content">
                    <div className="footer-brand">
                        <span className="brand-name">VCursor</span>
                        <p>© {new Date().getFullYear()} VCursor. All rights reserved.</p>
                    </div>
                    <div className="footer-links">
                        <Link href="/privacy">Privacy</Link>
                        <Link href="/terms">Terms</Link>
                        <Link href="https://discord.gg/Npf6PVsCYz" target="_blank">Discord</Link>
                        <Link href="/docs/cli">Docs</Link>
                    </div>
                </div>
            </footer>
        </main>
    );
}
